Add additional config
Aaronius/hyper-cat pull request #8
Opened 2017-10-26 22:48 UTC by towicode

For some reason... export.decorateConfig() does nothing, i couldn't even get it to be called. I'm not sure why... so I had to grab the config from the app. 

Adds config for rainbow alpha, music and stagger.

Add to hyper preferences

```
 catCursor: {
      stagger_height: 0, // how high to go up and down of nyan cat
      audio_enabled: false, // 
      orig_alpha: 0.5, // alpha of the rainbow
    },
```

2017-11-03 23:24 UTC, Aaronius commented on index.js
> +
Can we move this to the top of the file and then do 

```
const config = Object.assign({
  rainbowStaggerHeight: 2,
  rainbowMaxAlpha: 1,
  audioEnabled: true
}, e.remote.app.config.getConfig());
```

2017-11-03 23:24 UTC, Aaronius reviewed
Will you please use camelCase so it's consistent with the rest of the code?

2017-11-03 23:28 UTC, Aaronius commented on index.js
> -
Hmm...without this, the hypercat graphics shouldn't be working at all.

2017-11-03 23:31 UTC, Aaronius commented on index.js
>    }
Now that `audioEnabled` is a setting, I think we can get rid of the `hyper-cat-toggle-audio` terminal command. That would mean removing the function above and the `exports.middleware` stuff.

2017-11-03 23:32 UTC, Aaronius requested changes
I left several comments.

2017-11-22 23:36 UTC, towicode commented
@Aaronius I made most of the requested changes. I ran into an error (and it seems like you had run into it too) Where the Hyper Config wasn't immediately available as soon as hyper loaded. This caused an error and caused my config variable to be empty. I fixed it by putting the config assign in the decorate term block. Maybe you can figure out a better way to do it.

I also tried to remove the console command and that function.

2017-12-02 22:00 UTC, Aaronius approved these changes

2017-12-02 22:00 UTC, merged

2017-12-02 22:00 UTC, Aaronius commented
Thanks for contributing!